### ISSUE TITLE
PrimMonad instances?

### ISSUE THREAD

**Issue by axman6** [minad/writer-cps-full#2]
Not sure if this is the right repo, but it would be nice to have PrimMonad instances for the transforms in these packages. We currently have the following file:

```haskell
{-# LANGUAGE TypeFamilies #-}
{-# OPTIONS_GHC -Wno-orphans #-}

module Control.Monad.Trans.Writer.CPS.Orphans where

import Control.Monad.Trans.Class (lift)
import Control.Monad.Trans.Writer.CPS
import Control.Monad.Primitive 


instance PrimMonad m => PrimMonad (WriterT w m) where
  type PrimState (WriterT w m) = PrimState m
  primitive f = lift (primitive f)
```

**Comment by minad** [comment]
writer-cps-full just aggregates all the orphans. The PrimMonad orphans should go into a writer-cps-prim package. However note that Writer.CPS is also upstream in transformers since a few days.

http://hackage.haskell.org/package/transformers-0.5.6.2/docs/Control-Monad-Trans-Writer-CPS.html

**Comment by axman6** [comment]
Ah that's good news, we can probably change to the transformers version - I'll add an issue to `primitive` in that case.
